version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_CONN_STRING=mongodb://admin:admin@mongo:27017
      - DB_NAME=tinysd
    depends_on:
      - mongo
    volumes:
      - ./apps/api/saved-images:/app/saved-images

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
